- name: Install Helm (download latest stable version via script)
  raw: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash # Helm 설치 스크립트 GitHub에서 다운로드 및 서버에 설치
    sudo ln -sf /usr/local/bin/helm /usr/bin/helm || true                                 # Helm 심볼릭 링크 생성
  args:
    creates: /usr/local/bin/helm
  changed_when: false

- name: "Nginx Ingress Helm 저장소 추가 (Root)"
  ansible.builtin.command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx # Helm에 Nginx Ingress용 Chart repository 등록
  changed_when: true
