name: 7th-room-project-rds-deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v4

      # Terraform 설치
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4
          terraform_wrapper: false

      # Terraform 초기화 & 배포
      - name: Terraform Init & Apply
        id: apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      # RDS 엔드포인트 확인 (선택)
      - name: Output RDS Endpoint
        run: |
          cd terraform
          terraform output rds_endpoint
